### ISSUE TITLE
Data lost when using `maxUrlsPerFile` with a CsvSource

### ISSUE THREAD

**Issue by acanimal** [seifertd/site-mapper#2]
I was mading some tests generating sitemap from a CsvFile.  I updated the `maxUrlsPerFile` property to generate multiple sitemap files and saw one entry is lost per file.

For example, given a CSV file with:

```
line1, data1, url1
line2, data2, url2
line3, data3, url3
line4, data4, url4
```

and a `maxUrlsPerFile=2` the files generated are:

```
line1, data1, url1
line2, data2, url2
```

and

```
line4, data4, url4
```

**Comment by seifertd** [comment]
@acanimal This should be fixed in the latest releases, starting with https://github.com/seifertd/site-mapper/releases/tag/v2.3.3
